# Generated by Django 3.2.7 on 2021-09-26 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_clave', models.CharField(max_length=30, unique=True, verbose_name='Nombre Clave')),
                ('nombre_comercial', models.CharField(max_length=30, verbose_name='Nombre Comercial')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_final', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, max_length=80, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Confirmado'), (2, 'Desarrollo'), (3, 'Finalizado'), (4, 'Cancelado')], default=(1, 'Confirmado'))),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(blank=True, related_name='miembros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_final'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('estado', models.IntegerField(choices=[(1, 'Backlog'), (2, 'Diseño'), (3, 'Desarrollo'), (4, 'Testing'), (5, 'Review'), (6, 'Done')], default=(1, 'Backlog'))),
                ('fecha_inest', models.DateTimeField()),
                ('fecha_finest', models.DateTimeField()),
                ('duracion_est', models.DurationField(null=True)),
                ('duracion_real', models.DurationField(null=True)),
                ('descripcion', models.TextField(blank=True, max_length=120, null=True)),
                ('miembros', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projecto')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('file', models.FileField(upload_to='archivos')),
                ('descripcion', models.TextField(max_length=80, verbose_name='Archivo')),
                ('tipo', models.IntegerField(choices=[(1, 'Codigo'), (2, 'Modelos'), (3, 'Mockups'), (4, 'Documentos'), (5, 'Otros')], null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tarea')),
            ],
        ),
    ]
