# Generated by Django 3.2.7 on 2021-09-26 00:09

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{6,10}$')], verbose_name='Numero de documento')),
                ('telefono', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Por favor escribe el numero en el formato aceptado sin código de área ej: 3123456789', regex='^(3)([0-9]){9}$')], verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=70, verbose_name='Direccion')),
                ('incorporado', models.DateField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('groups', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
